### ISSUE TITLE
大佬问一下 为什么不采用阿里云的hls视频加密方案呢

### ISSUE THREAD

**Issue by martor-sv** [QingHeYang/TestHlsVideo#2]
https://help.aliyun.com/document_detail/59885.html

**Comment by QingHeYang** [comment]
这个emmmm...也得看业务场景，之前的项目分为两版，线上版用的保利威视，有cdn加速和hls加密。
线下版的不链接公网，所以不能走第三方，把视频源文件都给了甲方，但是还怕视频外泄，为了防止有人用ffmpeg把视频给合起来，所以要隐藏key文件，所以我才会弄出来个这么个方案。
要是线上的话，保利威视应该比阿里的便宜。

**Comment by martor-sv** [comment]
感谢大佬

**Comment by martor-sv** [comment]
简单的说就是把URL 的内容去掉，然后通过接口获取key的地址，然后在修改m3u8文件，在进行播放，没看明白你的本地地址是什么意思

**Comment by QingHeYang** [comment]
m3u8文件要在http服务器上面才能被播放器读取，把远程文件下载下来，改写后，我直接在手机开了http服务器，这样就能播放本地视频了，不然播放器不认m3u8的绝对路径
